### ISSUE TITLE
Build issue starting from rust 1.62.x

### ISSUE THREAD

**Issue by DmitryAstafyev** [infinyon/node-bindgen#195] opened 2022-07-04 12:02 UTC
Builds with rust <= 1.61.x - OK
Builds with rust >= 1.62.x - **FAIL**

Output
```
Compiling node-bindings v0.1.0 (/project/apps/rustcore/rs-bindings)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcNuBDcp/symbols.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.build_script_build.67163722-cgu.0.rcgu.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.build_script_build.67163722-cgu.1.rcgu.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.build_script_build.67163722-cgu.2.rcgu.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.build_script_build.67163722-cgu.3.rcgu.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.build_script_build.67163722-cgu.4.rcgu.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.build_script_build.67163722-cgu.5.rcgu.o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4.3wn5ycmmyti8y67f.rcgu.o" "-Wl,--as-needed" "-L" "/project/apps/rustcore/rs-bindings/target/release/deps" "-L" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/project/apps/rustcore/rs-bindings/target/release/deps/libnode_bindgen-c1b755e72269dba6.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnj_build-9f7d2494f7b992c8.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnj_core-03f1e22993313d0d.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libserde_json-a5ef54da1495436f.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libryu-5cf1aa6806b77e86.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libitoa-4a36602b2d48d7ac.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnum_bigint-afc45a198d7f9c5d.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnum_integer-8043249e647c0559.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnum_traits-f64dab11f266b914.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libinventory-e7745bd638d81db2.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libfluvio_future-67b29ccffb254041.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libtracing_subscriber-3fb8df255e81392e.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libsmallvec-ad13ff64ced3a2ea.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libsharded_slab-ba57813aa4bc362f.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libmatchers-0b52d95b9ede57c9.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libregex_automata-c852c9721e760b53.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libregex-13ccae4189f6b7a1.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libaho_corasick-676fb3f7f90f6169.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libregex_syntax-afbf0e58870d2e21.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libansi_term-cd72d93cec8fdef5.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libtracing-4503470e8167e27e.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libthread_local-a312c11f1bd38b43.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libtracing_log-5f596b11c3840481.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/liblazy_static-b6115d96285f84f3.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libtracing_core-4452d031ed5331cb.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libpin_project-c64cf9cb692df3ad.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_std-19d071860262972e.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_global_executor-149cafabd0edc407.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libblocking-f6a6049161b4f4d6.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libatomic_waker-cd8c5269726977b2.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnum_cpus-2be50a35ea174d17.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_executor-8fbda43b2b006ba7.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_task-8640c599fcf72fd3.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libcrossbeam_utils-718bbb87b83a42ef.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_process-695825356023206b.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libsignal_hook-42e1f7fe38c257e3.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libsignal_hook_registry-f217f44225390967.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_io-4a0392f68abc8743.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libslab-a66e9d861237249b.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libpolling-aea857fd57864ff4.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libonce_cell-09a1332365545ff0.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libsocket2-ffdf83a54758e16b.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_channel-a7b258fdfc9cade3.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libconcurrent_queue-111e1074f95d2f01.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libcache_padded-a1ec528a0fab0a00.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libasync_lock-122a17dc1c21246f.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libevent_listener-29b096106344bf07.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libpin_utils-a71d1bf286083944.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libkv_log_macro-024799df192b05c8.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libfutures_lite-99b950ce055c9265.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libmemchr-8613c794a68875de.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libfastrand-4dd0cbc777feb9f8.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libfutures_io-822c32344355f111.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libfutures_core-b13083a6cb64abf7.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libwaker_fn-f1b65db8df577d38.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libparking-d85cb5dd435d094b.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libpin_project_lite-4c655dd8c6bf824e.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libnj_sys-a952f0aec72636ea.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/liblog-8aec5359c7c8fba7.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libvalue_bag-b151c850f5be00c1.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libserde-23198ec0f806b86e.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/libcfg_if-244fb886a329b52e.rlib" "/project/apps/rustcore/rs-bindings/target/release/deps/liblibc-0b06180e1e915a72.rlib" "-Wl,--start-group" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7ca39ac42651c3df.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-62c6d032818141a1.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-50484fc03eb1eb5b.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-758be083b246d9c6.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-3cdf9a3c68f76e2d.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-3a1b74821c25a0e1.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-e046d82ebd84bb7f.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-a61cdd33cfa8394f.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-410c38f8df854235.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-f79d7458e122215f.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-7d24b750ce5b22e8.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-4c2aa1ea3133ab73.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-41220dc85a7f114f.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-230d004276c898f9.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-03ae30169a5438be.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-6f82c44b7818af35.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-1a0b7681f7efa789.rlib" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-83735dd4dae9b02c.rlib" "-Wl,--end-group" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-385029872275478f.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/username/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/project/apps/rustcore/rs-bindings/target/release/build/node-bindings-a550130a27eea1e4/build_script_build-a550130a27eea1e4" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: /project/apps/rustcore/rs-bindings/target/release/deps/libnj_core-03f1e22993313d0d.rlib(nj_core-03f1e22993313d0d.nj_core.a9398a91-cgu.8.rcgu.o): in function `nj_core::module::init_module':
          nj_core.a9398a91-cgu.8:(.text._ZN7nj_core6module11init_module17hd1272031f428fa6aE+0xa): undefined reference to `napi_module_register'
          /usr/bin/ld: /project/apps/rustcore/rs-bindings/target/release/deps/libnj_core-03f1e22993313d0d.rlib(nj_core-03f1e22993313d0d.nj_core.a9398a91-cgu.0.rcgu.o): in function `nj_core::basic::JsExports::define_property':
          nj_core.a9398a91-cgu.0:(.text._ZN7nj_core5basic9JsExports15define_property17h244b76202d4f3954E+0xf8): undefined reference to `napi_define_properties'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `node-bindings` due to previous error
```
Addition
```
uname -a
Linux xxx 5.15.49-1-lts #1 SMP Wed, 22 Jun 2022 12:52:35 +0000 x86_64 GNU/Linux

rustc --version
rustc 1.62.0 (a8314ef7d 2022-06-27)
```

**Comment by sehz** [comment] 2022-07-04 16:41
Thanks for the report. Will take look at it

**Comment by sehz** [comment] 2022-07-04 17:03
compiles ok on Mac but fails on Linux

**Comment by sehz** [comment] 2022-07-04 17:34
Looks like this is caused by an inventory crate issue but seems to be fixed in the latest version: https://github.com/dtolnay/inventory/issues/32.   I will try to update and see if it fixes the problem

**Comment by sehz** [comment] 2022-07-04 18:51
Updating inventory didn't seem to fix the issue.

**Comment by sehz** [comment] 2022-07-08 05:11
fixed with regression in windows

**Closed by sehz** 2022-07-08 05:11 UTC
Labels: build
