### ISSUE TITLE
Crashing on MacOS and electron.

### ISSUE THREAD

**Issue by StratusFearMe21** [infinyon/node-bindgen#144] opened 2021-04-03 14:42 UTC
It seems like no matter what I do I can't seem to stop MacOS from crashing on electron. I'm simply trying to make something similar to [iohook](https://github.com/wilix-team/iohook), but whenever an electron app is using the module, and it exits,  after about 2 minutes it spits out a crash report. [message.txt](https://github.com/infinyon/node-bindgen/files/6252747/message.txt). This is my code,
```rust
use std::sync::RwLock;

use device_query::{DeviceQuery, DeviceState};
use lazy_static::lazy_static;
use node_bindgen::derive::node_bindgen;
use rayon::iter::{IntoParallelIterator, ParallelIterator};

lazy_static! {
    static ref SHOULDSTOP: RwLock<bool> = RwLock::new(false);
}

#[node_bindgen]
async fn raw<F: Fn(Vec<String>)>(returnjs: F) -> bool {
    let device_state = DeviceState::new();
    let mut prev_keys = vec![];
    loop {
        let keys = device_state.get_keys();
        if *SHOULDSTOP.read().unwrap() {
            return true;
        } else if keys != prev_keys {
            let returnkeys: Vec<String> = keys
                .clone()
                .into_par_iter()
                .map(|x| format!("{}", x))
                .collect();
            returnjs(returnkeys);
        }
        prev_keys = keys;
    }
}

#[node_bindgen]
fn unload() {
    *SHOULDSTOP.write().unwrap() = true;
}
```
I'm out of ideas. please help

**Comment by StratusFearMe21** [comment] 2021-04-03 14:47
btw, these are some examples of where the code is being used
```typescript
globkey.raw((keypair: string[]) => {
        keypair.forEach(key => {
            let i = keypair.indexOf(key);
            keypair[i] = keypair[i].replace("L", "");
            keypair[i] = keypair[i].replace("R", "");
            keypair[i] = keypair[i].replace("Key", "");
        });
        keypair = keypair.sort();
        let ks = keypair.join().toLowerCase();
        let PTT = ks !== CURRENT_PTT_KEY_STRING;
        if (PREV_PTT_STATUS !== PTT) {
            bWindows.main.webContents.send("@voice/ptt_status_change", PTT);
            PREV_PTT_STATUS = PTT;
        }
    })
```
```typescript
app.on("window-all-closed", () => {
  globkey.unload();
  app.quit();
});
```
```typescript
if (!instanceLock) {
  if (process.env.hotReload) {
    app.relaunch();
  }
  globkey.unload();
  app.quit();
} else {
  app.on("ready", () => {
    localize().then(() => {
      createWindow();
      if (__prod__) autoUpdater.checkForUpdates();
    })
  });
  app.on("second-instance", (event, argv, workingDirectory) => {
    if (mainWindow) {
      if (process.env.hotReload) return mainWindow.close();
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });
}
```

**Comment by StratusFearMe21** [comment] 2021-04-03 15:07
An example output from the `.raw()` function would be `[ 'LControl', 'Key0' ]`

**Comment by sehz** [comment] 2021-04-03 16:35
Do you have code in the some public repo where I can try and run it?

**Comment by StratusFearMe21** [comment] 2021-04-03 16:38
Yes, [here](https://github.com/benawad/dogehouse/tree/staging/baklava)

**Comment by sehz** [comment] 2021-04-03 16:50
Can you give step by step instruction on how to reproduce this since I am not familiar with code base?

**Comment by StratusFearMe21** [comment] 2021-04-03 17:29
It should be enough to just open the app, then close it, then wait

**Comment by sehz** [comment] 2021-04-03 18:22
Encountered problem:
```
 yarn build:globkey
Usage Error: Couldn't find a script named "build:globkey".
```

**Comment by StratusFearMe21** [comment] 2021-04-03 20:34
Make sure you're running the commands inside of the **baklava** directory

**Comment by sehz** [comment] 2021-04-03 21:36
Ok, I was able to build and start.  It doesn't seem to crash.  Just open with empty screen.  Where is Rust code?

**Comment by StratusFearMe21** [comment] 2021-04-03 21:50
https://github.com/StratusFearMe21/globkey

**Comment by StratusFearMe21** [comment] 2021-04-03 21:51
Btw, pre-built binaries of the app can be found here https://github.com/benawad/dogehouse/releases

**Comment by sehz** [comment] 2021-04-04 01:32
Using release executable, I was able to start app.  

Can you add logging to trace what's happening to code ? 
It seems like looking logic, it may goes into infinite loop which leads to out of stack error, if `device_state` doesn't return properly keys.   Also suggest, put some limit to loop.

Other way is spawn `async` loop so not to block main thread

```
async fn raw<F: Fn(Vec<String>)>(returnjs: F) -> bool {
    let device_state = DeviceState::new();
    let mut prev_keys = vec![];
    loop {
        let keys = device_state.get_keys();
        if *SHOULDSTOP.read().unwrap() {
            return true;
        } else if keys != prev_keys {
            let returnkeys: Vec<String> = keys
                .clone()
                .into_par_iter()
                .map(|x| format!("{}", x))
                .collect();
            returnjs(returnkeys);
        }
        prev_keys = keys;
    }
}

```

**Comment by sehz** [comment] 2021-04-04 01:33
BTW, there is discord channel so we can collaborate better there

**Comment by StratusFearMe21** [comment] 2021-04-04 02:40
Okay, I'll switch to that

**Comment by sehz** [comment] 2021-04-04 04:21
Came out with simpler solution based on Discord discussion.  Closing for now.

**Closed by sehz** 2021-04-04 04:21 UTC
Labels: electron, triage
